import { Typography, Box } from '@mui/material'
import Head from 'next/head'
import WithFluidLayoutAndNoSidebar from '../components/WithFluidLayoutAndNoSidebar/WithFluidLayoutAndNoSidebar'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  return (
    <Box className={styles.container}>
      <Head>
        <title>HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <WithFluidLayoutAndNoSidebar />
      </Box>
    </Box>
  )
}
